alliance-genome/agr_java_software

- agr_api/src/main/java/org/alliancegenome/api/service/GeneService.java
> retrieve all alleles for a given gene

- agr_api/src/main/java/org/alliancegenome/api/controller/SiteMapController.java
> Master into Develop - Quick fix for sitemap

- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/DiseaseDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/FeatureDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/GeneDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/GoDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/PhenotypeAnnotationDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/PhenotypeDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/model/query/Pagination.java
This will make it easier for the UI to populate the phenotype table.
> agr-1060 create geneticEntity field on phenotypeAnnotations

- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_indexer/src/test/java/org/alliancegenome/indexer/FeatureTest.java
- agr_indexer/src/test/java/org/alliancegenome/indexer/GeneTest.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/FeatureTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/GeneTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/FeatureDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/GeneDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/Feature.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/Gene.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/FeatureRepository.java
Plus two small fixes:
change description to geneSynopsis for AGR-1048
fix to the "suffix stripping" for AGR-1037
>  AGR-1067 Add phenotype statements to gene & feature docs

- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/GOTerm.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/GoRepository.java
> Index GOTerms even if they don't have Gene Annotations

- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/OrthologyController.java
- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/OrthologyRESTInterface.java
- agr_api/src/test/java/org/alliancegenome/api/GeneTest.java
- agr_java_core/src/main/java/org/alliancegenome/core/service/JsonResultResponse.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/SpeciesType.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/Gene.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/OrthologousRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/view/OrthologView.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/view/OrthologyFilter.java
Refine the repository to retrieve ortho records in a paginated fashion.
> refine /api/homologs/taxonIDOne/taxonIDTwo

- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/SpeciesType.java
(cherry picked from commit d8e7f23c2934bc2effb002a2d5508a6d96354950)
> fix taxon ID for yeast

- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/settings/SiteIndexSettings.java
Hopefully, this will help in memory footprints for single shards.
> Added tweek to help reduce memory footprints

- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/GeneRESTInterface.java
- agr_api/src/main/java/org/alliancegenome/api/service/ExpressionService.java
handle null stage term in stage histogram
> filter out stage= null from stage histogram

- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/OrthologousRepository.java
(cherry picked from commit 77df2a535c538e5976527c23d634c5814830c28a)
> fix methods call query clause

- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/ExpressionController.java
- agr_api/src/main/java/org/alliancegenome/api/service/ExpressionService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/ExpressionSummaryGroup.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/ExpressionSummaryGroupTerm.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_api/src/test/groovy/org/alliancegenome/api/QueryMatchIntegrationSpec.groovy
- agr_api/src/test/java/org/alliancegenome/api/GeneTest.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/DiseaseTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/GeneTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/doclet/PublicationDoclet.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/AnnotationDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/GeneDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/mapping/GeneMapping.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/ExpressionBioEntity.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/DiseaseRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/GeneRepository.java
Split disease on gene doc into diseaseViaExperiment and diseaseViaOrthology
> Disease Via Orthology: Indexer

- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_indexer/src/test/groovy/org/alliancegenome/indexer/GeneDocumentIntegrationSpec.groovy
- agr_indexer/src/test/java/org/alliancegenome/indexer/GeneTest.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/GeneTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/GeneDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/mapping/GeneMapping.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/settings/SiteIndexSettings.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/Ontology.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/GeneRepository.java
@cmpich  We had a collision on both adding a p12, so I thought it might be time to start moving towards meaningful names to the match clauses.
> AGR-1196  Fix cellular component expression indexing for genes

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/GeneTranslator.java
> Fix related data counts & copy anatomy parents to GeneDocument

- agr_api/src/main/java/org/alliancegenome/api/service/GeneService.java
- agr_api/src/test/groovy/org/alliancegenome/api/DiseaseAnnotationSpec.groovy
- agr_api/src/test/groovy/org/alliancegenome/api/PhenotypeSpec.groovy
- agr_api/src/test/java/org/alliancegenome/api/PhenotypeTest.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/PhenotypeAnnotation.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/GeneticEntity.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/PhenotypeRepository.java
> AGR-1420 speed up the phenotype query, turn CrossReference for primary URL into attributes from collect()

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/RelatedDataServiceIntegrationSpec.groovy
- agr_indexer/src/main/java/org/alliancegenome/indexer/config/IndexerConfig.java
- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/DiseaseIndexer.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/AlleleTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/DiseaseTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/GeneTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/DiseaseDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/DiseaseDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/GeneDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/mapping/DiseaseMapping.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/Allele.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/DiseaseIndexerRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/DiseaseRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/GeneIndexerRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/GoRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/Neo4jRepository.java
plus fixes for related data and secondaryId for genes
> AGR-1343  Disease indexer flattened out

- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_indexer/src/test/groovy/org/alliancegenome/indexer/tests/integration/CategoriesAndFieldsIntegrationForLaterSpec.groovy
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/DiseaseDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/DiseaseIndexerRepository.java
> AGR-1449  Returned all the species to disease index

- Makefile
- agr_elasticsearch_util/src/main/java/org/alliancegenome/agr_elasticsearch_util/commands/index/SnapShotCommand.java
This code enables us to auto load the latest snapshot, after an index run.
> Added restore latest snapshot function

- agr_api/src/main/java/org/alliancegenome/api/controller/AlleleController.java
- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/AlleleRESTInterface.java
- agr_api/src/main/java/org/alliancegenome/api/service/AlleleService.java
- agr_api/src/main/java/org/alliancegenome/api/service/GeneService.java
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/AlleleWebServiceIntegrationSpec.groovy
- agr_api/src/test/java/org/alliancegenome/api/tests/integration/AlleleIT.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleCacheRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleRepository.java
create allele cache object and new endpoint for species as an argument
I am caching all allele objects as there are fewere than 200k and they seem to be cheap in memory.
> AGR-1538 create endpoint for retrieving alleles by species

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/RelatedDataServiceIntegrationSpec.groovy
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/dao/SearchDAO.java
Not sure I want this merged yet, mostly I want to see the automated test output to compare with odd difference between local site and staging.
> AGR-1637  Tweaked allele related data link to use name rather than nameKey

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/RelatedDataServiceIntegrationSpec.groovy
> AGR-1484  Fixed related data target field for diseases to genes

- agr_api/src/main/java/org/alliancegenome/api/controller/GeneController.java
- agr_api/src/main/java/org/alliancegenome/api/repository/DiseaseCacheRepository.java
- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/GeneRESTInterface.java
- agr_api/src/main/java/org/alliancegenome/api/service/DiseaseService.java
- agr_api/src/test/java/org/alliancegenome/api/tests/integration/DiseaseIT.java
Those two endpoints are not longer used in lieu of the new disease ribbon.
> AGR-1625 remove disease-via-orthology endpoints

- agr_indexer/Makefile
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/GeneIndexerRepository.java
Matched queries up between diseases on gene documents and genes listed on disease documents, updated neo docker image name
> AGR-1516 fixed disease lists on gene

- agr_api/src/main/java/org/alliancegenome/api/controller/DiseaseController.java
- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/DiseaseRESTInterface.java
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/DiseaseAnnotationIntegrationSpec.groovy
- agr_api/src/test/java/org/alliancegenome/api/tests/integration/DiseaseIT.java
- agr_cacher/src/main/java/org/alliancegenome/cacher/cachers/DiseaseCacher.java
- agr_java_core/src/main/java/org/alliancegenome/core/service/DiseaseAnnotationSorting.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/DiseaseAnnotationToTdfTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/ECOTerm.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/DiseaseRepository.java
> agm   (AGR-1687)

- agr_java_core/src/main/java/org/alliancegenome/core/service/AlleleSorting.java
- agr_java_core/src/main/java/org/alliancegenome/core/service/ModelAnnotationsSorting.java
added another ordering to defaultOrder for alleles
> AGR-1753 added Phenotypestatement ordering to default order

- agr_java_core/src/main/java/org/alliancegenome/core/service/ModelAnnotationFiltering.java
added evidenceCodeFilter, referenceFilter, sourceFilter, geneNameFilter
> Fixes AGR-1780

- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/ExpressionToTdfTranslator.java
> AGR-1668: added source column to expression download

- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/DiseaseAnnotationToTdfTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/PhenotypeAnnotationToTdfTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/PhenotypeDownloadRow.java
> AGR-1875 changes after pr comments

- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/DiseaseRESTInterface.java
restore swagger ui for allele table download on disease page
> AGR-1936 disease-allele table download

- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/QueryMatchIntegrationSpec.groovy
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleIndexerRepository.java
I added 4 new test cases, 1 works against the Neo database I have, the 3 MGI test alleles aren't available in Neo yet. Since we don't halt on tests failures, I thought I'd just put them in as well.
> AGR-2006 Removed requirement that alleles in search must have a relatonship to a gene

- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
and swapped default analyzer in for standardText fields
> AGR-2031 fixed GO branch in search results display

- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
to default to fix false match on UNIPROT id
> AGR-2096 changed search_analyzer on letterText

- agr_api/src/main/java/org/alliancegenome/api/service/AutoCompleteService.java
- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_indexer/src/main/java/org/alliancegenome/indexer/config/IndexerConfig.java
- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/VariantIndexer.java
- agr_java_core/src/main/java/org/alliancegenome/core/config/ConfigHelper.java
- agr_java_core/src/main/java/org/alliancegenome/core/config/Constants.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/AlleleTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/VariantTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/AlleleDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/GeneDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/IndexerCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/VariantIndexerRepository.java
Disabled by default, since they aren't going out with 3.1, but can be enabled with "-DINDEX_VARIANTS"
> AGR-2112  Added variant indexing classes

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/GeneDocumentCache.java
also only expanding biotype tree when a term is selected
> AGR-1314 Added 'unclassified XXXX' biotype values

- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/DiseaseRESTInterface.java
- agr_api/src/test/java/org/alliancegenome/api/tests/integration/DiseaseIT.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/Construct.java
> AGR-2151 add name attribute to construct object

- agr_api/src/main/webapp/swagger-ui/swagger-ui.css
- Changed css to match Alliance site colors.
> rebrand swagger ui

- agr_api/pom.xml
- agr_cacher/pom.xml
- agr_elasticsearch_util/pom.xml
- agr_indexer/pom.xml
- agr_intermine_data_extractor/pom.xml
- agr_java_core/pom.xml
- agr_schema_validation/pom.xml
- agr_variant_indexer/pom.xml
- pom.xml
> Cleanup of pom files

- agr_api/src/main/java/org/alliancegenome/api/service/ExpressionService.java
- agr_api/src/test/java/org/alliancegenome/api/tests/integration/AlleleIT.java
- agr_java_core/src/main/java/org/alliancegenome/core/config/ConfigHelper.java
- agr_java_core/src/main/java/org/alliancegenome/core/util/FileHelper.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/Construct.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleRepository.java
@cmpich IntelliJ should catch this kind of thing?
> Fix compile error

- agr_api/src/main/java/org/alliancegenome/api/service/ExpressionService.java
- agr_java_core/src/main/java/org/alliancegenome/core/config/ConfigHelper.java
@cmpich I think it was to early for me to be writing code. Merged wrong branch.
> Added fix code

- agr_java_core/src/main/java/org/alliancegenome/cache/repository/helper/ModelAnnotationFiltering.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/view/OrthologView.java
add Json property order annotation to get a reproducible order json attribute in the payload.
> AGR-2274 fix filtering evidence code on model table on diesease page

- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/SpeciesType.java
> modify SpeciesType.java for covid-19 data

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/VariantIndexer.java
- agr_java_core/src/main/java/org/alliancegenome/core/config/ConfigHelper.java
- agr_java_core/src/main/java/org/alliancegenome/core/config/Constants.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/AlleleTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/VariantTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/AlleleDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/IndexerCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleIndexerRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/VariantIndexerRepository.java
A rough draft implementation so that variant & search teams can get a look to fine tune the details
> AGR-2303 Initial commit combining allele & variant categories

- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/SpeciesType.java
change full name to SARS-CoV-2
> modifiy spciesTtpe for covid-19

- agr_api/src/main/java/org/alliancegenome/api/controller/GeneController.java
- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/GeneRESTInterface.java
added a new endpoint to get disease annotations based on gene id. I dont believe the ui needs to use this endpoint.
> AGR-2026 new disease endpoint for genes

- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/QueryMatchIntegrationSpec.groovy
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/QueryRankIntegrationSpec.groovy
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/QueryTokenizationIntegrationSpec.groovy
- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/AlleleIndexer.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/AlleleTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/AlleleDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/IndexerCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/settings/SiteIndexSettings.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleIndexerRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/VariantIndexerRepository.java
plus some variant tweaks and test fixes
> AGR-2320  Added additional construct fields to alleles

- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/QueryMatchIntegrationSpec.groovy
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleIndexerRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/DiseaseIndexerRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/GeneIndexerRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/ModelIndexerRepository.java
While I was passing through I made a lot of other relationships explicit also.
> AGR-2370 Exclude NOT associations between diseases and genes, alleles, and models.

- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/AlleleDownloadRow.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/AlleleToTdfTranslator.java
Added a new AlleleDownloadRow .java and added code to the AllelleTDFTranslator
> AGR-1712 Variant/Allele download table from gene page

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/test/groovy/org/alliancegenome/api/tests/integration/QueryRankIntegrationSpec.groovy
> Ranking fixes   AGR-2446, AGR-2448

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/AlleleIndexer.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/AlleleTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Mapping.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/Settings.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/settings/SiteIndexSettings.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/settings/VariantIndexSettings.java
- agr_variant_indexer/src/main/java/org/alliancegenome/variant_indexer/Main.java
- agr_variant_indexer/src/main/java/org/alliancegenome/variant_indexer/converters/human/HumanVariantContextConverter.java
- agr_variant_indexer/src/main/java/org/alliancegenome/variant_indexer/es/model/Sample.java
- agr_variant_indexer/src/main/java/org/alliancegenome/variant_indexer/es/model/TranscriptFeature.java
- agr_variant_indexer/src/main/java/org/alliancegenome/variant_indexer/es/model/VariantEffect.java
support for alterationType in Variant/Allele category,
some initial/minimal population of variant documents to work in site search
There's plenty more to do, but let's find out how this affects indexing time.
> Applied analysis from SiteSearchSettings to VariantIndexSettings

- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/indexer/DatasetIndexerRepository.java
also now indexing sample.sampleId rather than sample.primaryKey
> AGR-2473 don't index preferred cross references

- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/schema/VariantMapping.java
- agr_variant_indexer/src/main/java/org/alliancegenome/variant_indexer/converters/human/HumanVariantContextConverter.java
Also some tweaks to which fields are indexed and how
> AGR-2303 Populate variant facet fields

- agr_variant_indexer/src/main/java/org/alliancegenome/variant_indexer/converters/human/HumanVariantContextConverter.java
I'm not sure yet that we'll have any other type conversions, but I'd like to get this one in
> AGR-2532 Convert variant type DELINS to indel

- Dockerfile
- Dockerfile.agr_api
- Dockerfile.agr_cacher
- Dockerfile.agr_elasticsearch_util
- Dockerfile.agr_indexer
- Dockerfile.agr_schema_validation
- Dockerfile.agr_variant_indexer
- README.md
- agr_api/Makefile
- agr_api/README.md
- agr_cacher/Makefile
- agr_indexer/.env
- agr_indexer/Makefile
- agr_indexer/docker-compose.yml
- agr_intermine_data_extractor/Makefile
- agr_java_core/Makefile
- agr_variant_indexer/Makefile
More Makefile, Dockerfile and docker-compose updates to move away from dockerhub and into ECR as our docker image registry. Analogous to alliance-genome/agr_ansible_devops#15
> AGR-2528 java dockerhub => ECR code-changes

- agr_api/src/main/java/org/alliancegenome/api/controller/GeneController.java
- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/GeneRESTInterface.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/AlleleToTdfTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/TransgenicAlleleDownloadRow.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/VariantDownloadRow.java
Download for a single variant on allele page
Download for constructs on gene page
> Release4.0   AGR-2396, AGR-2431

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
Backend changes for the faucet exclusion feature
> AGR-2124 changes to allow excluding search faucets

- agr_java_core/src/main/java/org/alliancegenome/api/service/AlleleVariantSequenceColumnFieldMapping.java
Cannot reproduce the API error on my system.
> add debug statement

- agr_api/src/main/java/org/alliancegenome/api/controller/GeneController.java
- agr_api/src/main/java/org/alliancegenome/api/rest/interfaces/GeneRESTInterface.java
- agr_cacher/src/main/java/org/alliancegenome/cacher/cachers/AlleleCacher.java
- agr_java_core/src/main/java/org/alliancegenome/api/service/AlleleVariantSequenceColumnFieldMapping.java
- agr_java_core/src/main/java/org/alliancegenome/cache/repository/helper/AlleleVariantSequenceFiltering.java
- agr_java_core/src/main/java/org/alliancegenome/es/model/query/FieldFilter.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleRepository.java
Need to run SGD data as well now.
> AGR-2535 fix missing sequenceFeatureType

- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/InteractionRepository.java
remove some test comment from InteractionRepository.java
> remove some test comment of query to retrieve InteractionGeneJoin

- agr_cacher/src/main/java/org/alliancegenome/cacher/cachers/GeneOrthologCacher.java
- agr_java_core/src/main/java/org/alliancegenome/cache/repository/OrthologyCacheRepository.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/OrthologousRepository.java
fix AGR-2627 orthology stringencyFilter issue
> fix AGR-2627 stringencyFilter issue

- agr_java_core/src/main/java/org/alliancegenome/core/translators/tdf/AlleleToTdfTranslator.java
@christabone , fixed the compile error
> AGR-1854 fixed compile error

- agr_intermine_data_extractor/src/main/java/org/alliancegenome/data_extractor/translators/GeneTSVTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/DataExtractorRepository.java
> more info on genes

- agr_api/src/main/java/org/alliancegenome/api/service/helper/SearchHelper.java
- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/Indexer.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/ESDocument.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
Removed primary key as _id and added it to the response fields
> Autogenerated index

- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/IndexerCache.java
@adamgibs there might be a few of these PR's
> Fixed NPE's

- agr_java_core/src/main/java/org/alliancegenome/core/variant/converters/AlleleVariantSequenceConverter.java
Changed variant document gene field to use Gene.getNameKey
> AGR-2842 Changing variant genes field to include species abbreviation 

- agr_api/src/main/java/org/alliancegenome/api/service/SearchService.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/GeneDocumentCache.java
Also fixing one typo that prevents that biotype from showing up as a facet value.
> AGR-2460 - removing non-functional rnaBoost

- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/AlleleTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/core/translators/document/ModelTranslator.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/AlleleDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/IndexerCache.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/GeneticEntity.java
@oblodgett Allele indexing in the site indexer is updated. Very few changes not many. 
@adamgibs could you please test allele search features and make sure if nothing is missed.
> Site indexer2

- agr_java_core/src/main/java/org/alliancegenome/core/variant/service/AlleleVariantIndexService.java
So we try to adhere to some coding standards. I know this might seem like too much work, but it helps in documenting the code, readability, and understanding. Please see the following comments on the code.
> Added Code formatting

- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/indexer/AlleleIndexerRepository.java
Maybe a better way to do this.
> Added fix for indexer to finish

- agr_java_core/src/main/java/org/alliancegenome/es/util/IndexManager.java
@cmpich maybe there is a better way to do this with "Futures"?
> Indexer snapshot timeout fix

- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/AlleleIndexer.java
- agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/Indexer.java
- agr_java_core/src/main/java/org/alliancegenome/core/variant/converters/AlleleVariantSequenceConverter.java
- agr_java_core/src/main/java/org/alliancegenome/es/index/site/cache/GeneDocumentCache.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/node/TranscriptLevelConsequence.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/indexer/GeneIndexerRepository.java
The fix for this is on the loader side.
> Fix variant2

- agr_java_core/src/main/java/org/alliancegenome/neo4j/repository/AlleleRepository.java
> updated neo query

- agr_java_core/pom.xml
- agr_schema_validation/pom.xml
- pom.xml
Fixed lombok and elasticsearch dependencies with @oblodgett
> fixed some dependencies versions

- agr_java_core/src/main/java/org/alliancegenome/es/index/site/document/SearchableItemDocument.java
fix the allele count when search disease for scrum-251
> fix scrum-251 from release-5.1.0

- agr_api/src/test/java/org/alliancegenome/api/tests/integration/AlleleIT.java
- agr_java_core/src/main/java/org/alliancegenome/core/variant/converters/AlleleVariantSequenceConverter.java
- agr_java_core/src/main/java/org/alliancegenome/neo4j/entity/relationship/GenomeLocation.java
I know this change went in somehow it got lost.
> Removal of chromosome object from GL

- agr_intermine_data_extractor/pom.xml
JacksonFeature class not found, some issue with version incompatibility maybe (so), try it
> pom version mismatch problem?

- agr_api/src/main/java/org/alliancegenome/api/controller/DiseaseController.java
The fix I merged before had the logic inverted!
> SCRUM-2721: fixing SC
